In [1]:
!pip install numpy

In [3]:
import numpy as np

In [11]:
a = np.array([1,2,3]) # 1 row and 3 cols
print(a)
b = np.array([(1.5,2,3),(4,5,6)]) # 2 rows and 3 cols
print(b)
c  = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,1)]]) # 4 rows and 3 cols
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  1. ]]]


In [50]:
#Initial Placeholders
a = np.zeros((2,3)) #2 rows and 3 cols
b = np.ones((2,3,4)) #2 shapes, 3 rows and 4 cols
print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [7]:
d = np.arange(10,25,3) #between 10 to 25 and with difference of 3
print(d)

[10 13 16 19 22]


In [9]:
import numpy as np
g = np.linspace(12,5,6) #Between 12 to 5 with no.of intergers 6
h = np.linspace(1,7,3)
print(g)
print(h)

[12.  10.6  9.2  7.8  6.4  5. ]
[1. 4. 7.]


In [21]:
#Create 1D array
e = np.full((6),9) # ((col),element))
print(e)
print(e.ndim)

[9 9 9 9 9 9]
1


In [27]:
#Create 2D array
f = np.full((6,4),5) #((rows,col),element)
print(f)
print(f.ndim)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
2


In [35]:
#Create 3D array
j = np.full((3,5,5),4) #((shape,rows,cols),element)
print(j)
print(j.ndim)

[[[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]

 [[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]

 [[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]]
3


In [43]:
f = np.eye(4) #4X4 matrix
print(f)
f1 = np.eye(2) #2X2
print(f1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


In [62]:
a = np.random.random((3,4)) # print random decimals from 0 to 1 itself
b = np.random.random((1,1))
print(a) 
print(b)

[[0.61848447 0.46820515 0.0767649  0.34426213]
 [0.296624   0.39353449 0.86692459 0.16172667]
 [0.43709464 0.54520238 0.51940274 0.14095229]]
[[0.76515189]]


In [80]:
arr = np.array([[2,4,6],            
                [8,10,12],
                [14,16,18]])   #prints the shape of the matrix (rows , cols)
print(arr.shape)
arr1 = np.array([[10,12,13],
               [23,34,45],
               [45,56,67],
               [67,78,89]])
print(arr1.shape)

(3, 3)
(4, 3)


In [94]:
arr2 = np.array([[0 ,1 ,2],    
                 [3 ,5 ,7],
                 [9 ,11,13]])     #prints the size of the matrix (no.of elements in the matrix)
arr3 = np.array([[1,2,3,4,5],     
                 [2,6,22,72,2],
                 [2,435,54,7,3],
                 [23,45,76,56,98],
                 [12,45,54,71,4]])
print(arr2.size)
print(arr3.size)

9
25


In [110]:
arr4 = np.array([[1,2,3,4,5,6],     
                 [2,6,22,72,2,1],
                 [2,435,54,7,3,4],
                 [23,45,76,56,98,4],
                 [12,45,54,71,4,2]])    #prints length of the matrix (no.of rows)
print(len(arr4))
arr5 = np.array([[1,2,3],
                [3,6,1],
                [9,7,0]])
print(len(arr5))

5
3


In [15]:
#Access Array Elements
#We can access the elements by using index method 
arr = np.array([1,2,3,4,5])
print(arr[2]) #Giving index to detect value
print(arr[4])

3
5


In [31]:
#adding the elements using index
arr = np.array([2,4,6,8,10,12,14,16])
print(arr[1] + arr[3] - arr[7])
print(arr[0] * arr[2] - arr[5])
print(arr[2] ** arr[6])
print(arr[4] / arr[2])
print(arr[2] // arr[6])
print(arr[5] % arr[2])

-4
0
1054752768
1.6666666666666667
0
0


In [53]:
# Accessing elements using index in 2D
arr = np.array([[1,2,3,4,5],
                 [1,3,5,7,9],
                 [2,4,6,8,5],
                 [3,7,2,0,4]])
print(arr[1,3])
print(arr[3,3])
print(arr[0,2])

7
0
3


In [11]:
# Accessing elements using index in 3D
arr = np.array([[[1, 1, 3], [4, 3, 6]], 
                [[78, 81, 9], [10, 112, 12]]])

#Access by index
print(arr[1, 1, 1])
print(arr[1,1,0])

112
10


## Data Types

In [32]:
#string
arr = np.array([1,2,3,4,5,6,7], dtype = "S")
print(arr)
print(arr.dtype)

arr1 = np.array([6,3,6,9872,1,23,], dtype = "S")
print(arr1) 
print(arr1.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6' b'7']
|S1
[b'6' b'3' b'6' b'9872' b'1' b'23']
|S4


In [48]:
#integer
arr = np.array([2,6,3,2,7], dtype = "i4")
print(arr)
print(arr.dtype)

arr = np.array([53,76,4,8,34], dtype = "i4")
print(arr)
print(arr.dtype)

[2 6 3 2 7]
int32
[53 76  4  8 34]
int32


In [56]:
#Change data type from float to integer by using 'i' as parameter value:
arr = np.array([22.3,3.2,4.34,6.1,7.2])
print(arr.astype("i"))

arr1 = np.array([32.1,43.22,45.234,78.1,62,21])
newarr = arr1.astype("i")
print(newarr)

[22  3  4  6  7]
[32 43 45 78 62 21]


In [58]:
#Change data type from integer to boolean:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [92]:
#copy
arr = np.array([2,4,6,8,10,13])
newarr = arr.copy()
arr[0] = 23
print(arr)
print(newarr)

arr1 = np.array([12,54,345,76,345,123,234])
newarr1 = arr1.copy()
arr1[5] = 123456
print(arr1)
print(newarr1)

[23  4  6  8 10 13]
[ 2  4  6  8 10 13]
[    12     54    345     76    345 123456    234]
[ 12  54 345  76 345 123 234]


In [94]:
#view
arr = np.array([2,4,6,8,10,13])
newarr = arr.view()
arr[3] = 25
print(arr)
print(newarr)

[ 2  4  6 25 10 13]
[ 2  4  6 25 10 13]


## Reshaping arrays

In [103]:
#convert  the array from 1D to 2D
arr = np.array([2,4,6,8,0,1,3,5,7,9,12,23,34,45])
print(arr.reshape(7,2))

print(arr.reshape(2,7))

[[ 2  4]
 [ 6  8]
 [ 0  1]
 [ 3  5]
 [ 7  9]
 [12 23]
 [34 45]]
[[ 2  4  6  8  0  1  3]
 [ 5  7  9 12 23 34 45]]


In [115]:
#conert the array from 1D to 3D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr.reshape(2,2,5))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [125]:
#convert the array from 2D to 1D
arr = np.array([[2,3,4,5,6],
                [3,7,4,1,67],
                [2,5,4,1,7]])
print(arr.reshape(15))

[ 2  3  4  5  6  3  7  4  1 67  2  5  4  1  7]


In [129]:
#convert the array from 2D to 3D
arr = np.array([[12,23,44,6,7],
                [1,5,2,7,2],
                [12,76,234,876,23],
                [12,34,654,23,43]])
               
print(arr.reshape(5,2,2))

[[[ 12  23]
  [ 44   6]]

 [[  7   1]
  [  5   2]]

 [[  7   2]
  [ 12  76]]

 [[234 876]
  [ 23  12]]

 [[ 34 654]
  [ 23  43]]]


In [131]:
#convert the array from 3D to 1D
arr = np.array([[[123,2,34,23],[12,32,23,76]],
                [[31,23,54,12],[76,56,876,24]],
                [[324,76,3,8],[234,98,58,4]]])
print(arr.reshape(24))

[123   2  34  23  12  32  23  76  31  23  54  12  76  56 876  24 324  76
   3   8 234  98  58   4]


In [135]:
#convert the array from 3D to 2D
arr = np.array([[[123,2,34,23],[12,32,23,76]],
                [[31,23,54,12],[76,56,876,24]],
                [[324,76,3,8],[234,98,58,4]]])
newarr = arr.reshape(4,6)
print(newarr)

[[123   2  34  23  12  32]
 [ 23  76  31  23  54  12]
 [ 76  56 876  24 324  76]
 [  3   8 234  98  58   4]]


In [143]:
#Adding of two or more arrays
arr1 = np.array([[123,5,43,34],[23,43,65,2]])
arr2 = np.array([[43,23,54,23],[23,32,34,65]])
print(arr1 + arr2)
print(np.add(arr1,arr2))

[[166  28  97  57]
 [ 46  75  99  67]]
[[166  28  97  57]
 [ 46  75  99  67]]


In [147]:
#subtracting the arrays
arr1 = np.array([[123,5,43,34],[23,43,65,2]])
arr2 = np.array([[43,23,54,23],[23,32,34,65]])
print(arr1 - arr2)
print(np.subtract(arr1,arr2))

[[ 80 -18 -11  11]
 [  0  11  31 -63]]
[[ 80 -18 -11  11]
 [  0  11  31 -63]]


In [157]:
#multiplication of arrays
arr1 = np.array([[123,5,43,34],[23,43,65,2]])
arr2 = np.array([[43,23,54,23],[23,32,34,65]])
print(arr1 * arr2)
print(np.multiply(arr1,arr2))

[[5289  115 2322  782]
 [ 529 1376 2210  130]]
[[5289  115 2322  782]
 [ 529 1376 2210  130]]


In [171]:
#Squaring of arrays
arr1 = np.array([[123,5,43,34],[23,43,65,2]])
arr2 = np.array([[43,23,54,23],[23,32,34,65]])
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[[11.09053651  2.23606798  6.55743852  5.83095189]
 [ 4.79583152  6.55743852  8.06225775  1.41421356]]
[[6.55743852 4.79583152 7.34846923 4.79583152]
 [4.79583152 5.65685425 5.83095189 8.06225775]]


In [175]:
#division of arrays
arr1 = np.array([[123,5,43,34],[23,43,65,2]])
arr2 = np.array([[43,23,54,23],[23,32,34,65]])
print(arr1 / arr2)
print(np.divide(arr1,arr2))

[[2.86046512 0.2173913  0.7962963  1.47826087]
 [1.         1.34375    1.91176471 0.03076923]]
[[2.86046512 0.2173913  0.7962963  1.47826087]
 [1.         1.34375    1.91176471 0.03076923]]


In [193]:
#Slicing the elements from an array
arr = np.array([2,3,4,5,6,7,8,9])
print(arr[2:8]) #n-1
print(arr[:9])
print(arr[3:])
print(arr[-6:-1])
print(arr[::7])
print(arr[1:5:6])

[4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[4 5 6 7 8]
[2 9]
[3]


In [197]:
#slicing 2D array
arr = np.array([[12,23,44,6,7],
                [1,5,2,7,2],
                [12,76,234,876,23],
                [12,34,654,23,43]])
print(arr[2 , 0:4])
print(arr[0 , -4:-1])

[ 12  76 234 876]
[23 44  6]


In [203]:
#slicing 3D array
arr = np.array([[[123,2,34,23],[12,32,23,76]],
                [[31,23,54,12],[76,56,876,24]],
                [[324,76,3,8],[234,98,58,4]]])
print(arr[1,0,2:5])
print(arr[2,1,0:5])
print(arr[0,0,-4:-1])

[54 12]
[234  98  58   4]
[123   2  34]
